// <auto-generated />
using System;
using CourierMax.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CourierMax.Infrastructure.Migrations
{
    [DbContext(typeof(CourierMaxDbContext))]
    [Migration("20260623042709_AddReferenceSeedData")]
    partial class AddReferenceSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CourierMax.Domain.Entities.CityDistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("DistanceFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Origin", "Destination")
                        .IsUnique();

                    b.ToTable("CityDistances", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Destination = "Medellín",
                            DistanceFee = 12000m,
                            DistanceKm = 480m,
                            Origin = "Bogotá"
                        },
                        new
                        {
                            Id = 2,
                            Destination = "Cali",
                            DistanceFee = 9000m,
                            DistanceKm = 360m,
                            Origin = "Bogotá"
                        },
                        new
                        {
                            Id = 3,
                            Destination = "Barranquilla",
                            DistanceFee = 20000m,
                            DistanceKm = 950m,
                            Origin = "Bogotá"
                        },
                        new
                        {
                            Id = 4,
                            Destination = "Cali",
                            DistanceFee = 8000m,
                            DistanceKm = 310m,
                            Origin = "Medellín"
                        },
                        new
                        {
                            Id = 5,
                            Destination = "Barranquilla",
                            DistanceFee = 15000m,
                            DistanceKm = 650m,
                            Origin = "Medellín"
                        },
                        new
                        {
                            Id = 6,
                            Destination = "Barranquilla",
                            DistanceFee = 18000m,
                            DistanceKm = 900m,
                            Origin = "Cali"
                        });
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Drivers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "María López"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Carlos Ruiz"
                        });
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PackageType")
                        .HasColumnType("int");

                    b.Property<decimal>("PackageWeight")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SenderAddress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ServiceType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.HasIndex("VehicleId");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.ShipmentStatusHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("PreviousStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ShipmentStatusHistories", (string)null);
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CurrentVolumeM3")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CurrentWeightKg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxVolumeM3")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("MaxWeightKg")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasFilter("[DriverId] IS NOT NULL");

                    b.HasIndex("Plate")
                        .IsUnique();

                    b.ToTable("Vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVolumeM3 = 0m,
                            CurrentWeightKg = 0m,
                            DriverId = 1,
                            MaxVolumeM3 = 10m,
                            MaxWeightKg = 500m,
                            Plate = "ABC-123"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVolumeM3 = 0m,
                            CurrentWeightKg = 0m,
                            DriverId = 2,
                            MaxVolumeM3 = 6m,
                            MaxWeightKg = 300m,
                            Plate = "DEF-456"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CurrentVolumeM3 = 0m,
                            CurrentWeightKg = 0m,
                            DriverId = 3,
                            MaxVolumeM3 = 15m,
                            MaxWeightKg = 800m,
                            Plate = "GHI-789"
                        });
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Shipment", b =>
                {
                    b.HasOne("CourierMax.Domain.Entities.Driver", null)
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CourierMax.Domain.Entities.Vehicle", null)
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("CourierMax.Domain.ValueObjects.Dimensions", "PackageDimensions", b1 =>
                        {
                            b1.Property<int>("ShipmentId")
                                .HasColumnType("int");

                            b1.Property<decimal>("HeightCm")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PackageHeight");

                            b1.Property<decimal>("LengthCm")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PackageLength");

                            b1.Property<decimal>("WidthCm")
                                .HasColumnType("decimal(10,2)")
                                .HasColumnName("PackageWidth");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("PackageDimensions")
                        .IsRequired();
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.ShipmentStatusHistory", b =>
                {
                    b.HasOne("CourierMax.Domain.Entities.Shipment", null)
                        .WithMany("StatusHistories")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("CourierMax.Domain.Entities.Driver", "Driver")
                        .WithOne("Vehicle")
                        .HasForeignKey("CourierMax.Domain.Entities.Vehicle", "DriverId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CourierMax.Domain.Entities.Shipment", b =>
                {
                    b.Navigation("StatusHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
